### ISSUE TITLE
Legacy configmaps

### ISSUE THREAD

**Issue by rafal11ck** [openebs/monitoring#128]
I deployed chart version 0.4.13 and was met by 
```
 kubectl get configmaps -n observability  | grep openebs
openebs-monitoring-cstor-overview                         1      49m
openebs-monitoring-cstor-pool                             1      49m
openebs-monitoring-cstor-volume                           1      49m
openebs-monitoring-cstor-volume-replica                   1      49m
openebs-monitoring-jiva-volume                            1      49m
openebs-monitoring-localpv-workload                       1      49m
openebs-monitoring-lvmlocalpv-pool                        1      49m
openebs-monitoring-ndm                                    1
```

I though most of those should not exist based on https://github.com/openebs/monitoring/issues/116

values
```yaml
  values:
    kube-prometheus-stack: #I have that separate
      install: false
    node-problem-detector:
      install: false
    openebsMonitoringAddon:
      lvmLocalPV:
        enabled: true
        dashboards:
          enabled: true
        alertRules:
          enabled: true
        serviceMonitor:
          enabled: true
      zfsLocalPV:
        enabled: false
      dashboards:
        enabled: false
      npd:
        enabled: false
```
I've got grafana operator look at configmaps as a result following dashboards are deployed 

![Image](https://github.com/user-attachments/assets/fe0b9b7c-094d-426b-94ef-226f011269db)
